name: Metrics
on:
  # æ¯å¤©å‡Œæ™¨ 0 ç‚¹æ›´æ–°
  schedule: [{cron: "0 0 * * *"}]
  # å…è®¸ä½ æ‰‹åŠ¨ç‚¹å‡»æŒ‰é’®æ›´æ–°
  workflow_dispatch:
  # å½“ä¸»åˆ†æ”¯æœ‰ push æ“ä½œæ—¶æ›´æ–°
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Felixzijunliang
          template: classic
          
          # åŸºç¡€è®¾ç½®
          base: header, repositories
          config_timezone: Asia/Shanghai
          
          # è¯­è¨€è®¾ç½®
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, gnuplot
          plugin_languages_limit: 8
          
          # è´¡çŒ®è¶‹åŠ¿å›¾
          plugin_lines: yes
          
          # ã€ğŸ‘‡ é‡ç‚¹ä¿®æ”¹è¿™é‡Œã€‘æµé‡ç»Ÿè®¡è®¾ç½®
          plugin_traffic: yes
          plugin_traffic_clones: yes      # å¼ºåˆ¶æ˜¾ç¤ºå…‹éš†æ•°
          plugin_traffic_clones_days: 14  # ç»Ÿè®¡è¿‡å»14å¤©
          plugin_traffic_views: yes       # å¼ºåˆ¶æ˜¾ç¤ºæµè§ˆæ•°
          plugin_traffic_views_days: 14   # ç»Ÿè®¡è¿‡å»14å¤©
