name: Metrics
on:
  # 每天凌晨 0 点更新
  schedule: [{cron: "0 0 * * *"}]
  # 允许你手动点击按钮更新
  workflow_dispatch:
  # 当主分支有 push 操作时更新
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # 你的用户名
          user: Felixzijunliang
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          # 插件配置
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_limit: 8
          plugin_lines: yes
